apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.nginx.deployment.app }}
spec:
  replicas: {{ .Values.nginx.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nginx.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.deployment.app }}
    spec:
      containers:
        - name: {{ .Values.nginx.deployment.container.name }}
          image: {{ .Values.nginx.deployment.container.image }}
          imagePullPolicy: {{ .Values.nginx.deployment.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.nginx.deployment.container.port }}
          volumeMounts:
            - mountPath: {{ .Values.nginx.deployment.container.mountPath }}
              name: {{ .Values.nginx.deployment.container.volumeMountName }}
      volumes:
        - name: {{ .Values.nginx.deployment.volumes.name }}
          hostPath:
            path: {{ .Values.nginx.deployment.volumes.path }}
---

apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.nginx.service.name }} 
   namespace: {{ .Values.namespace }}
spec:
   selector:
      app: {{ .Values.nginx.service.app }}
   ports:
      - port: {{ .Values.nginx.service.port }}
        targetPort: {{ .Values.nginx.service.targetPort }}

