apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.moviePostgres.statefulset.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.moviePostgres.statefulset.label }}
spec:
  serviceName: {{ .Values.moviePostgres.statefulset.spec.serviceName }}
  replicas: {{ .Values.moviePostgres.statefulset.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.moviePostgres.statefulset.spec.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.moviePostgres.statefulset.spec.app }}
    spec:
      containers:
        - image: {{ .Values.moviePostgres.statefulset.container.image }}
          name: {{ .Values.moviePostgres.statefulset.container.name }}
          ports:
          - containerPort: {{ .Values.moviePostgres.statefulset.container.port }}
          env:
            - name: {{ .Values.moviePostgres.statefulset.env.user.nameKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.moviePostgres.secret.name }}
                  key: {{ .Values.moviePostgres.statefulset.env.user.nameKey }}
                  optional: false
            - name: {{ .Values.moviePostgres.statefulset.env.password.nameKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.moviePostgres.secret.name }}
                  key: {{ .Values.moviePostgres.statefulset.env.password.nameKey }}
                  optional: false
            - name: {{ .Values.moviePostgres.statefulset.env.dbName.nameKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.moviePostgres.secret.name }}
                  key: {{ .Values.moviePostgres.statefulset.env.dbName.nameKey }}
                  optional: false
          volumeMounts:
            - mountPath: {{ .Values.moviePostgres.statefulset.volumeMounts.mountPath }}
              name: {{ .Values.moviePostgres.statefulset.volumes.name }}
      volumes:
        - name: {{ .Values.moviePostgres.statefulset.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.moviePostgres.statefulset.volumes.pvcName }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moviePostgres.service.nameApp }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.moviePostgres.service.nameApp }}
spec:
  selector:
    app: {{ .Values.moviePostgres.service.nameApp }}
  ports:
  - name: {{ .Values.moviePostgres.service.nameApp }}
    port: {{ .Values.moviePostgres.service.port }}
    targetPort: {{ .Values.moviePostgres.service.targetPort }}
  clusterIP: {{ .Values.moviePostgres.service.clusterIP }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.moviePostgres.secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.moviePostgres.secret.type }}
data:
  POSTGRES_USER: {{ .Values.moviePostgres.secret.user }}
  POSTGRES_PASSWORD: {{ .Values.moviePostgres.secret.password }}
  POSTGRES_DB: {{ .Values.moviePostgres.secret.db }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.moviePostgres.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.moviePostgres.pvc.accessMode }}
  storageClassName: {{ .Values.moviePostgres.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.moviePostgres.pvc.storage }}

